#!/bin/sh

set -e

case "$1" in
  configure)
    :
    	service apparmor restart || true
    	aa-disable usr.bin.r > /dev/null || true
    ;;
  abort-upgrade | abort-remove | abort-deconfigure)
    :
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

#DEBHELPER#

exit 0

