#! /bin/sh

set -e

case "$1" in
  remove | abort-install)
    :

      ### When removing these files manually they won't be reinstalled when 
      ### the package is installed again later without purging
      ### rm -f /etc/apparmor.d/usr.bin.r
      ### rm -Rf /etc/apparmor.d/rapparmor*
      
      rm -f /etc/apparmor.d/disable/usr.bin.r
      service apparmor restart || true
    ;;
  purge | disappear | upgrade | failed-upgrade | abort-upgrade)
    :
    ;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

#DEBHELPER#

exit 0